on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * * # Every day
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.1'
          bundler-cache: true
      - name: Cache Run Data
        id: cache-run-data
        uses: actions/cache@v3
        with:
          path: tmp
          key: tmp
      - name: Install dependencies
        run: bundle install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::615749242856:role/github-actions-blog-s3
          aws-region: us-east-1
      - name: Sync & Publish
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
        run: |
          bundle exec bin/sync-and-publish
